version: '3.3'
services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v3.2.1
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
  tyk-redis:
    image: redis:5.0-alpine
    networks:
      - tyk
    ports:
      - 6379:6379
  tyk-identity-broker:
    image: tykio/tyk-identity-broker:s1.2
    ports:
      - 3010:3010
    networks:
      - tyk
    volumes:
      - ./identity-broker/tib.conf:/opt/tyk-identity-broker/tib.conf
      - ./identity-broker/profiles.json:/opt/tyk-identity-broker/profiles.json
    depends_on:
      - tyk-gateway
      - tyk-redis

networks:
  tyk:
